config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    get '', to: 'courses#index', as: '/' 
    resources :courses
    resources :sections
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :sections ,dependent: :destroy # when a course is deleted all sections of it will destroy
	validates :title,  presence: true, length: { maximum: 25 }, uniqueness: true
  	validates :description, presence: true, length: { maximum: 100}
  	validates :duration , presence: true
end

app/models/section.rb
class Section < ActiveRecord::Base
	belongs_to :course
	default_scope -> { order('created_at DESC') }
	validates :title, presence: true , length: { maximum: 200 }
	#validates :course_id, presence: true
	validates :videourl, presence: true 
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  
  def index
  	@course = Course.all
  end

  def show
  	@course = Course.find(params[:id])
  end

  def new
  	@course = Course.new
  end
  
  def create
    @course = Course.new(course_params)    
    if @course.save
      flash[:success] = "Course is added successfully!"
      redirect_to [:admin, @course]
    else
      render 'new'
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(course_params)
      flash[:success] = "Course is updated successfully!"
      redirect_to [:admin_course]
    else
      render 'edit'
    end
  end

  def destroy
    Course.find(params[:id]).destroy
    flash[:success] = "Course deleted successfully"
    redirect_to [:admin_courses]
  end

  private
    def course_params
       params.require(:course).permit(:title,:description,:duration)
    end
 

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
  end
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < ApplicationController
  
  def index
  	@section = Section.all
  end

  def show
  	@section = Section.find(params[:id])
  end

  def new
  	@section = Section.new
  end
  
  def create
    @section = Section.new(section_params)    # Not the final implementation!
     if @section.save
       flash[:success] = "Section is added successfully!"
       redirect_to [:admin, @section]
    else
      render 'new'
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(section_params)
      flash[:success] = "Section is updated successfully!"
      redirect_to [:admin_section]
    else
      render 'edit'
    end
  end

  def destroy
    Section.find(params[:id]).destroy
    flash[:success] = "Section deleted successfully"
    redirect_to [:admin_sections]
  end

  private
    def section_params
       params.require(:section).permit(:title,:course_id,:videourl)
    end
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/courses/edit.html.erb
<h1>Edit Course</h1> 
<%= form_for([:admin, @course]) do |c| %>
<table>
    
    	<%= render 'shared/error_messages' ,object: c.object %>
		<tr>
		     <td> <%= c.label :title %></td>
		     <td> <%= c.text_field :title %></td>
		</tr>

		<tr>
		     <td><%= c.label :description %></td>
		      <td><%= c.text_area :description %></td>
		</tr>

		<tr>
		     <td><%= c.label :duration %></td>
		      <td><%= c.text_field :duration %></td>
		</tr>
		 
	    <tr>
	     	<td> <%= c.submit "Save changes", class: "btn btn-large btn-primary" %></td>
	     	<td><%= link_to 'Cancel', admin_courses_path, class: "btn btn-info" %></td>
	    </tr>
    
</table>  
<% end %>

app/views/admin/courses/index.html.erb
<h1>Course List</h1> <br>

<%= link_to 'Add New Course', new_admin_course_path, class: "btn btn-info" %>&nbsp;&nbsp;
 <%= link_to 'Dashboard(Home)', admin_path, class: "btn btn-info" %>
 <br><br>  
<% if @course.count == 0 %>
<%= "No record presents" %>
<% else %>
<table border=1 cellspaceing="5">
	<tr>
		<td>Title</td>
		<td>Description</td>
		<td>Duration</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<% @course.each do |course| %>
		<tr>
			<td><%= link_to course.title , [:admin, course] %></td>
			<td><%= course.description %></td>
			<td><%= course.duration %></td>
			<td><%= link_to "Edit", edit_admin_course_path(course) %></td>
			<td><%= link_to "delete", [:admin, course], method: :delete, data: { confirm: 'Are you sure?' } %>	
			<td><%= link_to "Add Sections" , new_admin_section_path(:course_id=> course.id)  %></td>
			<td><%= link_to "View Sections" , admin_sections_path(:course_id=> course.id)  %></td>
		</tr>
	<% end %>
</table>
<% end %>	
 <br><br>
 
  

app/views/admin/courses/new.html.erb
<h1>Add New Course</h1> 
 <%= form_for([:admin, @course]) do |c| %>
<table>
   
    	<%= render 'shared/error_messages' ,object: c.object %>
		<tr>
		     <td> <%= c.label :title %></td>
		     <td> <%= c.text_field :title %></td>
		</tr>

		<tr>
		     <td><%= c.label :description %></td>
		      <td><%= c.text_area :description %></td>
		</tr>

		<tr>
		     <td><%= c.label :duration %></td>
		      <td><%= c.text_field :duration %></td>
		</tr>
		 
	    <tr>
	     	<td> <%= c.submit "Create new course", class: "btn btn-large btn-primary" %></td>
	     	<td><%= link_to 'Cancel', admin_courses_path, class: "btn btn-info" %></td>
	    </tr>
    
</table>  
<% end %>

app/views/admin/courses/show.html.erb
<h1>Show Course</h1> <br><br>

<table border=0 cellspaceing="5">
	<tr>
		<td>Title</td><td>:</td><td><%= @course.title %></td>
	</tr>	
	<tr>
		<td>Description</td><td>:</td><td><%= @course.description %></td>
	</tr>	
	<tr>
		<td>Duration</td><td>:</td><td><%= @course.duration %></td>
	</tr>
</table>	

<div class="span8">
    <% if @course.sections.any? %>
      <h3>Sections (<%= @course.sections.count %>)</h3>
      <%#= #render @sections %>
      
    <% end %>
  </div>

<br>
<td><%= link_to 'Back', admin_courses_path, class: "btn btn-info" %></td>
<br>

app/views/admin/dashboard/index.html.erb
<h1>Administration</h1> 
<ul> 
	<li><%= link_to 'Manage Courses' , admin_courses_path  %></li> 
	<li><%= link_to 'Manage Sections', admin_sections_path  %></li>
</ul> 

app/views/admin/sections/edit.html.erb
<h1>Edit Section</h1> 
 <%= form_for([:admin, @section]) do |s| %>
<table>
   
    	<%= render 'shared/error_messages', object: s.object %>
		<tr>
		     <td> <%= s.label :title %></td>
		     <td> <%= s.text_field :title %></td>
		</tr>

		<tr>
		     <td> <%= s.label :VideoUrl %></td>
		     <td> <%= s.text_field :videourl %></td>
		</tr>
				
	    <tr>
	     	<td><%= s.submit "Update new section", class: "btn btn-large btn-primary" %></td>
	     	<td><%= link_to 'Cancel', admin_courses_path, class: "btn btn-info" %></td>
	    </tr>
    
</table>  
<% end %>

app/views/admin/sections/index.html.erb
<h1>Section List</h1> <br>

 <%= link_to 'Dashboard(Home)', admin_path, class: "btn btn-info" %>
 <br><br>  
<% if @section.count == 0 %>
<%= "No record presents" %>
<% else %>
<table border=1 cellspaceing="5">
	<tr>
		<td>Title</td>
		<td>Video Url</td>
		<td></td>
		<td></td>
	</tr>
	<% @section.each do |section| %>
		<tr>
			<td><%= link_to section.title , [:admin, section] %></td>
			<td><%= section.videourl %></td>
			<td><%= link_to "Edit", edit_admin_section_path(section) %></td>
			<td><%= link_to "delete", [:admin, section], method: :delete, data: { confirm: 'Are you sure?' } %>	
		</tr>
	<% end %>
</table>
<% end %>	
 <br><br>
 
  

app/views/admin/sections/new.html.erb
<h1>Add New Section</h1> 
 <%= form_for([:admin, @section]) do |s| %>
<table>
   
    	<%= render 'shared/error_messages', object: s.object %>
		<tr>
		     <td> <%= s.label :title %></td>
		     <td> <%= s.text_field :title %></td>
		</tr>

		<tr>
		     <td> <%= s.label :VideoUrl %></td>
		     <td> <%= s.text_field :videourl %></td>
		</tr>

		<tr>
			<td> <%= s.hidden_field :course_id, :value => params[:course_id] %></td>
		</tr>
				
	    <tr>
	     	<td><%= s.submit "Create new section", class: "btn btn-large btn-primary" %></td>
	     	<td><%= link_to 'Cancel', admin_courses_path, class: "btn btn-info" %></td>
	    </tr>
    
</table>  
<% end %>

app/views/admin/sections/show.html.erb
<h1>Show Section</h1> <br><br>

<table border=0 cellspaceing="5">
	<tr>
		<td>Title</td><td>:</td><td><%= @section.title %></td>
	</tr>	
	<tr>
		<td>Video Url</td><td>:</td><td><%= @section.videourl %></td>
	</tr>	
	
</table>	
<br>
<td><%= link_to 'Back', admin_courses_path, class: "btn btn-info" %></td>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devlip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>